### ISSUE TITLE
Program crashes with error on Main branch

### ISSUE THREAD

**Issue by manali-teke** [manali-teke/MyScheduleBot#6]
Got error while running the program on main- schedulebot.py
MyScheduleBot\src\functionality\highlights.py", line 81
    await channel.send(f"You have {e['name']} scheduled , from {e['startTime']} to {e['endTime']} {'' if e['url'] is None or not e['url'] else "\n Link: " + e['url']}")

                        ^
SyntaxError: unexpected character after line continuation character

Expected: Bot should be started with welcome message popped up on channel.

**Comment by adityajson** [comment]
The error occurs for python version <  3.12. Updated the code to make it compatible for older versions of python.

**Comment by manali-teke** [comment]
Resolved
